//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeGerenciamentoDePeixes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PEIXES
    {
        public int id_peixe { get; set; }
        public int id_usuario { get; set; }
        public string nm_peixe { get; set; }
        public string ds_especie { get; set; }
        public string ds_descricao { get; set; }
        public Nullable<double> vl_peso { get; set; }
        public Nullable<int> vl_tamanho { get; set; }
        public Nullable<System.DateTime> ds_data_morte { get; set; }
        public byte[] img { get; set; }
        public string ds_status_saude { get; set; }
        public string ds_doenca { get; set; }
        public System.DateTime ds_data_aquisicao { get; set; }
    
        public virtual TB_USUARIO TB_USUARIO { get; set; }
    }
}
